### ISSUE TITLE
Determine why database refresh / imports are now taking 30+ minutes to complete when running wp_refresh_single.

### ISSUE THREAD

**Issue by imcbride** [middlebury/wordpress-tools#1]

**Comment by cg923** [comment]
I've been following this article to try to speed up the process.  No luck yet:
https://dev.mysql.com/doc/refman/5.7/en/optimizing-innodb-bulk-data-loading.html

Edit:  After further fussing I have the hunch that setting lock-tables to false could be a culprit in the slowdown.  I'm sure there's a good reason for keeping it off, but it may be worth looking at.  Here is another little bit of info that I've attempted to implement (no success yet) that seems like it's heading in the right direction:
https://dba.stackexchange.com/a/173882

I also tried adding --opt to the mysqldump command, which is supposed to speed things up but I didn't notice any difference.
